<?php
/**
 * @file
 * Code for the GSB Feature ACT Display feature.
 */

include_once 'gsb_feature_act_display.features.inc';

/**
 * Implements hook_form_alter().
 */
function gsb_feature_act_display_form_alter(&$form, &$form_state, $form_id) {
  $display_handler = array('panel_pane_1', 'panel_pane_2', 'panel_pane_3');
  if ($form_id == 'views_exposed_form' && $form_state['view']->name == 'gsb_act_project_listing' && (in_array($form_state['view']->display_handler->display->id, $display_handler))) {
    $form['secondary']['field_act_status_value']['#weight'] = -105;
    $form['#action'] = '';
    $form['secondary']['done'] = array(
      '#type' => 'submit',
      '#value' => t('Done'),
    );
    $form['secondary']['clear-all'] = array(
      '#type' => 'button',
      '#value' => t('Clear All'),
    );
    unset($form['field_act_status_value']['#options']['All']);
  }
}

function gsb_feature_act_display_form_validate(&$form, &$form_state) {
  $form_state['values']['arguments']['nid'] = $form_state['values']['exposed']['arguments']['nid'];
  if ($form_state['values']['cta_title'] != '' && $form_state['values']['cta_url'] == '') {
    form_set_error('cta_url', t('CTA Url is required.'));
  }
  if ($form_state['values']['cta_title'] == '' && $form_state['values']['cta_url'] != '') {
    form_set_error('cta_title', t('CTA title is required.'));
  }
}

/**
  * Implements hook_form_FORM_ID_alter().
  */
function gsb_feature_act_display_form_views_content_views_panes_content_type_edit_form_alter(&$form, &$form_state) {

  // Alter 'ACT Project filters' content pane settings form.
  if ($form_state['pane']->subtype == 'act_project_filters-act_project_filters_pane'
    && $form_state['view']->name == 'act_project_filters'
    && $form_state['view']->current_display == 'act_project_filters_pane') {
    //$form['exposed']['widget_title']['#field_prefix'] = 'Block Title';
    $form['arguments']['nid']['#description'] = 'Separate Node IDs with commas and no spaces.';
    $form['exposed']['filter-field_act_status_value']['#description'] = 'leave blank to display all';
    $form['exposed']['arguments'] = $form['arguments'];
    $form['arguments']['#access'] = FALSE;
    $form['#validate'][] = 'gsb_feature_act_display_form_validate';
    $form['exposed']['filter-title']['#weight'] = -99;
    $form['exposed']['arguments']['#weight'] = -98;
    $form['context']['#access'] = FALSE;
    $form['fields_override']['title']['#default_value'] = TRUE;
    $form['fields_override']['title']['#access'] = FALSE;
    $form['fields_override']['field_act_organization_type_1']['#access'] = FALSE;
    $form['fields_override']['nothing']['#title'] = t('Organization Type');
    $form['fields_override']['field_act_project_focus']['#access'] = FALSE;
    $form['fields_override']['nothing_1']['#title'] = t('Project Focus');

    if ($form_state['op'] == 'add') {
      $form['fields_override']['field_act_org_location']['#default_value'] = FALSE;
      $form['fields_override']['field_link_single']['#default_value'] = FALSE;
      $form['fields_override']['field_act_round']['#default_value'] = FALSE;
      $form['fields_override']['field_location']['#default_value'] = FALSE;
      $form['fields_override']['field_act_project_type']['#default_value'] = FALSE;
      $form['fields_override']['field_act_project_focus']['#default_value'] = FALSE;
      $form['fields_override']['field_act_organization_type']['#default_value'] = FALSE;
    }

    $conf = $form_state['conf'];
    $form['override_title']['#weight'] = -105;

    $form['CTA'] = array(
      '#type' => 'fieldset',
      '#title' => t('CTA'),
    );
    $form['CTA']['cta_title'] = array(
      '#title' => t('Text'),
      '#type' => 'textfield',
      '#description' => 'Enter an action statement.',
      '#weight' => 1,
      '#default_value' => !empty($conf['cta_title']) ? $conf['cta_title'] : '',
    );
    $form['CTA']['cta_url'] = array(
      '#title' => t('URL'),
      '#type' => 'textfield',
      '#weight' => 2,
      '#default_value' => !empty($conf['cta_url']) ? $conf['cta_url'] : '',
    );

    $form['#submit'][] = 'act_project_filters_pane_config_submit';
  }
}

/**
 * Submit handler for views_content_views_panes_content_type_edit_form.
 *  - Save title link field in pane config.
 */
function act_project_filters_pane_config_submit($form, &$form_state) {
  $form_state['conf']['cta_url'] = $form_state['values']['cta_url'];
  $form_state['conf']['cta_title'] = $form_state['values']['cta_title'];
}

/**
 * Implements hook_panels_pane_content_alter().
 *  - Alter Act Project Filters content pane title to be linked to a custom URL.
 */
function gsb_feature_act_display_panels_pane_content_alter($content, $pane, $args, $context) {
  if ($content && $content->subtype == 'act_project_filters-act_project_filters_pane') {
    if (!empty($pane->configuration['cta_title'])) {
      $url_parts = drupal_parse_url($pane->configuration['cta_url']);
      $url_parts['html'] = TRUE;
      $content->content['#markup'] .= '<div class="list-cta">' . l($pane->configuration['cta_title'], $url_parts['path'], $url_parts) . '</div>';
    }
  }
}
