<?php
/**
 * @file
 * Code for the GSB Feature ACT Display feature.
 */

include_once 'gsb_feature_act_display.features.inc';

/**
 * Implements hook_form_alter().
 */
function gsb_feature_act_display_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'views_exposed_form' && $form_state['view']->name == 'gsb_act_project_listing' && $form_state['view']->display_handler->display->id == 'panel_pane_1') {
    unset($form['field_act_status_value']['#options']['All']);
  }
}

function gsb_feature_act_display_form_validate(&$form, &$form_state) {
  $form_state['values']['arguments']['nid'] = $form_state['values']['exposed']['arguments']['nid'];
}

/**
  * Implements hook_form_FORM_ID_alter().
  */
function gsb_feature_act_display_form_views_content_views_panes_content_type_edit_form_alter(&$form, &$form_state) {

  // Alter 'ACT Project filters' content pane settings form.
  if ($form_state['pane']->subtype == 'act_project_filters-act_project_filters_pane' && $form_state['view']->name == 'act_project_filters' && $form_state['view']->current_display == 'act_project_filters_pane') {

    //$form['exposed']['widget_title']['#field_prefix'] = 'Block Title';
    $form['arguments']['nid']['#description'] = 'Separate Node IDs with commas and no spaces.';
    $form['exposed']['filter-field_act_status_value']['#description'] = 'leave blank to display all';
    $form['exposed']['arguments'] = $form['arguments'];
    $form['arguments']['#access'] = FALSE;
    $form['#validate'][] = 'gsb_feature_act_display_form_validate';
    $form['exposed']['filter-title']['#weight'] = -99;
    $form['exposed']['arguments']['#weight'] = -98;
    $form['context']['#access'] = FALSE;
    $form['fields_override']['title']['#default_value'] = TRUE;
    $form['fields_override']['title']['#access'] = FALSE;
    $form['fields_override']['field_act_organization_type_1']['#access'] = FALSE;
    $form['fields_override']['nothing']['#title'] = t('Organization Type');
    $form['fields_override']['field_act_project_focus']['#access'] = FALSE;
    $form['fields_override']['nothing_1']['#title'] = t('Project Focus');

    if ($form_state['op'] == 'add') {
      $form['fields_override']['field_act_org_location']['#default_value'] = FALSE;
      $form['fields_override']['field_link_single']['#default_value'] = FALSE;
      $form['fields_override']['field_act_round']['#default_value'] = FALSE;
      $form['fields_override']['field_location']['#default_value'] = FALSE;
      $form['fields_override']['field_act_project_type']['#default_value'] = FALSE;
      $form['fields_override']['field_act_project_focus']['#default_value'] = FALSE;
      $form['fields_override']['field_act_organization_type']['#default_value'] = FALSE;
    }

    $conf = $form_state['conf'];
    $item['title_link'] = array(
      '#title' => t('URL'),
      '#type' => 'textfield',
      '#weight' => -100,
      '#default_value' => !empty($conf['title_link']) ? $conf['title_link'] : '',
    );
    $form['override_title']['#weight'] = -105;
    $form = gsb_misc_fixes_associative_insert($form, 'override_title_text', $item);

    $form['#submit'][] = 'act_project_filters_pane_config_submit';
  }
}

/**
 * Submit handler for views_content_views_panes_content_type_edit_form.
 *  - Save title link field in pane config.
 */
function act_project_filters_pane_config_submit($form, &$form_state) {
  $form_state['conf']['title_link'] = $form_state['values']['title_link'];
}

/**
 * Implements hook_panels_pane_content_alter().
 *  - Alter Act Project Filters content pane title to be linked to a custom URL.
 */
function gsb_feature_act_display_panels_pane_content_alter($content, $pane, $args, $context) {
  if ($content && $content->subtype == 'act_project_filters-act_project_filters_pane') {
    if (!empty($pane->configuration['title_link'])) {
      $url_parts = drupal_parse_url($pane->configuration['title_link']);
      // Don't sanitize the title. It will get sanitized later.
      $url_parts['html'] = TRUE;
      $content->title = l($content->title, $url_parts['path'], $url_parts);
    }
  }
}
